### ISSUE TITLE
About cardiac dataset

### ISSUE THREAD

**Issue by Mike-Xiao** [paulhager/MMCL-Tabular-Imaging#25]
Hi author,

 Thank you so much for open source your nice work! I have registered my UKBB account, but now I am a bit confused about what image dataset to down load and how to process those raw data to tables like" data_train_eval_tabular: cardiac_features_train_imputed_noOH_CAD.csv?", I can find the tabular features through the UK Biobank Field ID you listed in the appendix, but how to search for the exact image dataset? And how to process those UKBB data to dataset like DVM data as you showed in “create_dvm_dataset.ipynb” ?  

Really appreciate you help!

**Comment by paulhager** [comment]
I've uploaded the code now, you can also find it in the data folder. It's been a while since I've ran it, so I can't guarantee that it will work first try. There have also been subjects that have removed themselves from the UKBB since I did the project, so exact reproducibility on your end will be difficult. But generally: 
1. You will need to download all short axis files from UKBB and then process them using https://github.com/baiwenjia/ukbb_cardiac/tree/master to determine ES and ED frames. 
2. Then you can run my code to generate the imaging dataset. 
3. You will also need to request and download all of the necessary tabular features in your basket.
4. Then you can run my code to generate the tabular dataset.
5. Then you can run my code to generate the labels and the splits.

**Comment by Mike-Xiao** [comment]
Thanks a lot！
